<?php

namespace ifpb\pweb\provaBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class provaController__JMSInjector
{
    public static function inject($container) {
        $instance = new \ifpb\pweb\provaBundle\Controller\provaController();
        return $instance;
    }
}
